name: yc-pca
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - pandoc
  - texlive-core
  - pyarrow
  - jupyter
  - ipykernel
  - statsmodels
  - python-dotenv
  - pip
  - pip:
      - fredapi
      - plotly
      - nelson-siegel-svensson
      - black
      - ruff
      - pre-commit